
linkin-org: an emacs workflow with fast, reliable links.

* linkin-org: typical workflows

*** Just downloaded some file?
  In dired, store the file (~linkin-org-store~) to move the file in your store directory (whatever the variable ~linkin-org-store-directory~ equals to).
  This just copied a link: paste it in a .org file and follow the link (~linkin-org-open-link~) with your cursor on it to retrieve your file.
  While storing the file, linkin-org added an id at the beginning of your file name: your link will still work if you rename or move the file around (needs to stay inside ~linkin-org-store-directory~ though).

*** Just wrote something you'd like to go back to later?
  Go one line above and store that line (~linkin-org-store~) to insert an id there.
  This just copied a link: paste it in a .org file and follow the link (~linkin-org-open-link~) to go back exactly where you were.
  That link will always get you exactly at the right location.

*** Reading something interesting in a pdf?
  Select the text with your mouse and store the pdf location (~linkin-org-store~, works with the emacs package [[https://github.com/vedang/pdf-tools][pdf-tool]]).
  Following the copied link (~linkin-org-open-link~) gets you to the right page and highlight the words you were reading.
  If the pdf file has an id then your link will always work: perfect for fast, reliable reading notes.

*** and more
   Store and replay precise moments of a videos (with mpv), launch musics with links (with mpd, organically turn your org notes into playlists), save selected text or feeds with one key press.


* Installing linkin-org
with straight
#+begin_src emacs-lisp
(use-package linkin-org
  :straight (linkin-org
	     :type git
	     :host github
	     :repo "Judafa/linkin-org")
  :config
  ;; change this to the directory you want to store your things into
  (setq linkin-org-store-directory "~/")

  ;; workflow tips (warning: I'm an evil user)
  (define-key global-map (kbd "C-l") 'linkin-org-open-link)
  (define-key global-map (kbd "C-n") 'org-next-link)
  (define-key global-map (kbd "C-p") 'org-previous-link)

  
  (nvmap :keymaps 'override :prefix "SPC"
    ;; "f"   '(range-dans-fourre-tout :which-key "Range la chose sous le curseur dans le Fourre-tout")
    "f"   '(hydra-fourre-tout/body :which-key "Ouvre un menu hydra pour ranger dans le Fourre-tout")
    )

  
  
)
#+end_src


