* linkin-org

An emacs workflow with fast, reliable links.

** Store and retrieve information at the speed of light
- *Just downloaded some file?*

  Run ~linkin-org-store~ in dired to move the file in your store directory (whatever the variable ~linkin-org-store-directory~ equals to).
  Doing so, you just copied a link: paste that link in a .org file and run ~linkin-org-open-link~ with your cursor on the link to retrieve your file.
  Also, you just added an id at the beginning of your file name: your link will still work if you rename or move the file (needs to stay inside ~linkin-org-store-directory~ though).
- *You just wrote something you'd like to go back to later?*

  Run ~linkin-org-store~ one line above to insert an id there.
  Doing so, you also just copied a link: paste it in a .org file and follow the link with ~linkin-org-open-link~ to go back to that important place.
  Following the link will always get you exactly at the right location.
- *Reading something interesting in a pdf?*

  Select the excerpt with your mouse and run ~linkin-org-store~ (need to use pdf-tool).
  You just copied a link to the exact words you were reading.
  Follow the link (~linkin-org-open-link~) to  go the right page and highlight what you selected.
- *and more*

   store and replay precise moments of a videos (with mpv), launch musics with links (with mpd, organically turn your org notes into playlists)


** installing linkin-org
with straight
#+begin_src emacs-lisp
(use-package linkin-org
  :straight (linkin-org
	     :type git
	     :host github
	     :repo "Judafa/linkin-org")
  :config
  ;; change this to the directory you want to store your things into
  (setq linkin-org-store-directory "~/")

  ;; workflow tips
  )
)
#+end_src


