linkin-org --- unbreakable links. 

* Overview

A link is a piece of text that redirects to some data.


Links are amazing: you can access your local data directly from your written notes, making it so easy to organize and retrieve your files.
Problem is, a link stops working when the linked data was renamed or moved to another place.


Linkin-org solves this problem.
Linkin-org allows you to access your local data --- directories, files or lines --- with *reliable* links that never break.
The links are made reliable thanks to ids attached to your data.


In a few words, linkin-org is:
- *reliable*: your links just always work.
  It takes a bit of discipline (see the [[#the-4-golden-rules-how-reliable-are-the-links-exactly][4 golden rules]]) and you should be ok seeing ids in your file names and in your notes.
  You get used to it!
- *fully distributed*: rename, move, modify your files from literally anywhere (emacs, a file browser, a cloud server, ...) without risk to break your links.
  All you have to do is to not change or remove the ids.
- *non-intrusive*: you can organize your files with other methods in parallel (directory hierarchy, file-naming, etc) without problem.
  The only noticeable difference is, the files and directories that are reliably linked have an id in their names.
- *simple*: there are two main commands: ~linkin-org-store~ and ~linkin-org-get~


linkin-org suggests a simple, blazingly fast workflow to store and retrieve your data: store the data (~linkin-org-store~), paste the link in your note, retrieve the data (with standard link opening command ~org-open-at-point-global~).

* Everything with 2 commands

linkin-org provides two main commands:
- ~linkin-org-store~ stores what you have under the cursor so that links towards it become *reliable*.
  It works on a file or a directory (in a dired buffer) and a line in an editable file (org, markdown, python, whatever).
  It directly copies the link in your clipboard so you can paste it right away.
  It adds an id to your data (changing your file name or the current editable line) so links towards it become reliable.

- ~linkin-org-get~ copies a link towards what you have under the cursor in your clipboard; it does not modify your data.
  This works on a file (in dired), a line in an editable file, on selected words in a pdf (using the extension [[https://github.com/Judafa/linkin-org-pdf-link][linkin-org-pdf-link]] in [[https://github.com/vedang/pdf-tools][pdf-tools]]), on a music track in mingus (using the extension [[https://github.com/Judafa/linkin-org-music-link][linkin-org-music-link]] in [[https://github.com/pft/mingus][mingus]]).
  The link may not be reliable; it will be reliable if you called ~linkin-org-store~ beforehand on the data.

* How does it work?
An id system makes sure that your links will always work even if you move, rename or modify the linked data (see the [[#the-4-golden-rules-how-reliable-are-the-links-exactly][4 golden rules]]).
The ids used by linkin-org are time stamps that are precise to the second.
Concretely, a file that you can reliably access via a link has an id in its name, like:
#+begin_src example
20250425T155433--filename.txt
#+end_src
and a line that you can reliably access via a link (here with a python syntax) looks like:
#+begin_src python
# [id:20250425T160020] link gets you there
#+end_src


When you open a link that contains an outdated path (e.g., the linked file was renamed or moved), linkin-org will try to resolve the link using the ids in the path.
For that, linkin-org will attempt two heuristics.
First, it tries to resolve the path with local id search (fast, always works if the file was only renamed); Second, it performs an exhaustive recursive search in the directories listed in the variable ~linkin-org-search-directories~ (slower, always works as long as the file is in one of those directories).



* Typical workflow samples

*** Just downloaded some file?
Put your cursor on the file in dired and store it (~linkin-org-store~) to move the file in your store directory (whatever the variable ~linkin-org-store-directory~ equals to).
By doing this, you copied a link: paste it in a file, opening the link retrieves your file.
Also while storing the file, linkin-org added an id at the beginning of your file name: your link will still work if you rename or move the file around.

*** Just wrote something you'd like to go back to later?
Go one line above and store the current line (~linkin-org-store~) to insert an inline id.
By doing this, you just copied a link: paste it in a file, opening the link goes back exactly where you were.

*** Reading something interesting in a pdf?
Select the text with your mouse and get a link towards the pdf location (~linkin-org-get~).
Opening the copied link gets you to the right page and highlight the words you were reading.
If the pdf file has an id then your link will always work: perfect for fast, reliable reading notes.
This works with the extension [[https://github.com/Judafa/linkin-org-pdf-link][linkin-org-pdf-link]] and the pdf reader [[https://github.com/vedang/pdf-tools][pdf-tools]].

* Installing linkin-org
with melpa
#+begin_src emacs-lisp

(use-package linkin-org
  :config
  ;; the first element of that list is the default storing place
  (setq linkin-org-store-directory (list "~/"))
  ;; set this to a list of directories that will be searched (in order) to resolve broken links
  (setq linkin-org-search-directories (list "~/Downloads" "~/"))
  ;; so that plain search triggered by opening a link work in org files 
  (setq org-link-search-must-match-exact-headline nil)
  ;; ;; uncomment those two lines of code to open your linked files as if you opened them from dired
  ;; (setq linkin-org-open-links-as-in-dired-p t)
  ;; (setq linkin-org-opening-file-function-in-dired #'dired-open-file)
  ;; ;; determines where the ids are positioned in the file name, can be 'head or 'tail. defaults to 'head
  ;; (setq linkin-org-id-position-in-file-name 'tail)

  ;; start the linkin-org global mode
  (linkin-org-global-mode 1)
  )




;; ;; uncomment to install other link types
;; (use-package linkin-org-pdf-link
;;   :straight (linkin-org-pdf-link
;; 	     :type git
;; 	     :host github
;; 	     :repo "Judafa/linkin-org-pdf-link")
;;   )

;; (use-package linkin-org-music-link
;;   :straight (linkin-org-music-link
;; 	     :type git
;; 	     :host github
;; 	     :repo "Judafa/linkin-org-music-link")
;;   )
#+end_src

with straight
#+begin_src emacs-lisp
(use-package linkin-org
  :straight (linkin-org :type git :host github :repo "Judafa/linkin-org")
  :config
  ;; the first element of that list is the default storing place
  (setq linkin-org-store-directory (list "~/"))
  ;; set this to a list of directories that will be searched (in order) to resolve broken links
  (setq linkin-org-search-directories (list "~/Downloads" "~/"))
  ;; so that plain search triggered by opening a link work in org files 
  (setq org-link-search-must-match-exact-headline nil)
  ;; ;; uncomment those two lines of code to open your linked files as if you opened them from dired
  ;; (setq linkin-org-open-links-as-in-dired-p t)
  ;; (setq linkin-org-opening-file-function-in-dired #'dired-open-file)
  ;; ;; determines where the ids are positioned in the file name, can be 'head or 'tail. defaults to 'head
  ;; (setq linkin-org-id-position-in-file-name 'tail)

  ;; start the linkin-org global mode
  (linkin-org-global-mode 1)
  )




;; ;; uncomment to install other link types
;; (use-package linkin-org-pdf-link
;;   :straight (linkin-org-pdf-link
;; 	     :type git
;; 	     :host github
;; 	     :repo "Judafa/linkin-org-pdf-link")
;;   )

;; (use-package linkin-org-music-link
;;   :straight (linkin-org-music-link
;; 	     :type git
;; 	     :host github
;; 	     :repo "Judafa/linkin-org-music-link")
;;   )
#+end_src


* Dependencies
Linkin-org does not have dependencies and works out-of-the-box with emacs 30 and higher.
For fast link recovery, it is recommended to have [[https://github.com/sharkdp/fd][fd]] installed.

* The 4 golden rules: How Reliable are the links exactly?

There are *four golden rules*.
If you respect them, your links will always work.
1. *Do not change or remove the ids.*
   An id in a file name or a directory name looks like 20250425T155433, an inline id inside a file content looks like id:20250425T160020.
   Ids are what enables linkin-org to reliably retrieve your data.
   So tampering with the ids breaks your links.
2. *Make sure that each id is unique.*
   linkin-org uses time stamps to generate the ids.
   The time stamps are precise to the second.
   So if you space id creations by one second, there will be no problem.
   But be careful when you start copying files: if you dont change the file name of the copied file, you end up with two similar ids leading to undefined behaviors when opening a link.
   In that case, remove the id of the copied file by hand and create another id for that file.
3. *Attach an id before you create a link*.
   The reverse order will break your links.
   Nevertheless, you can create links without any ids involved (use ~linkin-org-get~ on the data).
   But if you later decide to attach an id to the data, all your previous links towards the data will be broken.
4. *Keep your data inside the directories marked for id resolving*.
   Those directories are listed in ~linkin-org-search-directories~.
   linkin-org recursively searches throughout those directories to find your data in last resort.
   By default, ~linkin-org-store~ always suggests to store your data in one of those directories.
   # No link is broken if the linked data has an id and lies inside those directories.

With its builtin commands, linkin-org suggests a simple workflow that respects all four golden rules at once: whenever you want to keep a data in your local memory, take the habit to run ~linkin-org-store~ and then paste the link in a written note.



* A few tips
Here are personal tips, this is a matter of preference.
- Bind ~org-next-link~ and ~org-previous-link~ to comfortable keys.
  When you start to have many links, it gives the not unsatisfying sensation that you merged org with dired.
  Here are my bindings (for an evil user):
  #+begin_src emacs-lisp
  (nvmap :keymaps 'override :prefix "SPC"
    "f"   '(linkin-org-store :which-key "Store the data at point")
    "y"   '(linkin-org-get :which-key "Get a link towards the data at point in your clipboard")
    )

  (nvmap :keymaps 'override
    "C-n"   '(org-next-link :which-key "Jump to the next org link")
    "C-p"   '(org-previous-link :which-key "Jump to the previous org link")
    "C-l"   '(org-open-at-point-global :which-key "Open the link at point")
    )
  #+end_src
- Attach your ids as deep as possible in your file system, best directly in the file name.
  Usually, best not to over-engineer with ids everywhere along the file paths.
- Sometimes, you dont want to attach ids directly to the files (e.g. a file in a git repository); then, your can attach the id to the folder that contains it.
- Place the most relevant link at the top of the note.
  It can be a link towards some data you access a lot in the context of the note.
  It can also be a link toward a precise place of the note itself --- for instance, my reading notes always start with a link that takes me to the end of the note; I then go one line up and open the pdf link I pasted there last time I stopped reading to go back where I was.
  With this, your fingers quickly learn the automation "go to the note -> org-next-link -> org-open-at-point-global" to access a data quickly.


* Inspirations and Related Packages

My biggest inspiration is the [[https://github.com/protesilaos/denote][Denote]] package by Protesilaos Stavrou, and also the [[https://github.com/org-roam/org-roam][org-roam]] package.
Both of those packages use ids that are directly attached to the file names for a note-taking purpose.
Linkin-org's default syntax is taken from Denote --- by default, linkin-org's path resolving system is compatible with both denote and org-roam syntaxes.

I also took inspiration from the [[https://github.com/NixOS/nix][nix package manager]], and the [[https://github.com/NixOS/nix][nixos]] operating system.
Those softwares use cryptographic hashes to uniquely identify packages.
The cryptographic hashes are simply attached to the directory containing the package, which gives a reliable way to refer to a given package.

