* linkin-org

An emacs workflow with fast, reliable links.

** An addictive workflow with links
linkin-org enables that kind of workflow:
- *Just downloaded some file?* Hit `M-x linkin-org-store` in dired to move the file in your store directory (whatever the variable `linkin-org-store-directory` equals to).
  Doing so, you just copied a link to the file: paste the link in a .org file and hit `M-x linkin-org-open-link` to retrieve your file.
  You also added an id at the beginning of your file name: you can rename or change the file location, your link will still work (not outside of `linkin-org-store-directory` though).
- *The document you edit (org note, code, ...) gets lengthy?* Hit `M-x linkin-org-store` on a line before an important info to insert a commented id there.
  You just copied a file to that precise location, paste it a .org and follow the link (`M-x linkin-org-open-link`) to go back to that important place.
  Following the link triggers a search for the commented id: you will always go back exactly where you want in the file.
- *Reading some interesting things in a pdf* (using the pdf-tools package)? Select the excerpt with your mouse and hit `M-x linkin-org-store`.
  You just copied a link to the exact words you were reading.
  Follow the link (`M-x linkin-org-open-link`) to open the pdf (if not open yet), go the right page and highlight what you selected.
- *Many other things*: store and replay precise moments of a videos (with mpv), launch musics with links (with mpd, organically turn your org notes into playlists)


** installing linkin-org
with straight
#+begin_src emacs-lisp
(use-package linkin-org
  :straight (linkin-org
	     :type git
	     :host github
	     :repo "Judafa/linkin-org")
  :config
  ;; change this to the directory you want to store your things into
  (setq linkin-org-store-directory "~/")
  )
)
#+end_src


